name: Build

on:
  push:
    branches:
      - '**'
      - '!main'
  workflow_dispatch:

jobs:
  build:
    name: Build / Node ${{ matrix.node }}
    strategy:
      matrix:
        node: ['16']

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install pnpm
        run: npm install -g pnpm@^8.1.0

      - run: |
          pnpm install --no-frozen-lockfile
          pnpm run build
